# set the environment for login shells
[ -v DOT_DEBUG ] && echo '-> .zprofile'

case "$(uname)" in
    'Linux')
        export PLATFORM='linux'
        export PROJECTS_HOME="${HOME}"
        ;;
    'Darwin')
        export PLATFORM='darwin'
        export PROJECTS_HOME="${HOME}/data/dev/Projects"
        ;;
    *)
        export PLATFORM='unknown'
        ;;
esac

if [ "$PLATFORM" = "darwin" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
