# set the environment for login shells
[ -v DOT_DEBUG ] && echo '-> .zprofile'

case "$(uname)" in
    'Linux')
        export PLATFORM='linux'
        export PROJECTS_HOME="${HOME}"
        ;;
    'Darwin')
        export PLATFORM='darwin'
        export PROJECTS_HOME="${HOME}/Projects"
        ;;
    *)
        export PLATFORM='unknown'
        ;;
esac

# Homebrew shellenv is initialised in .zshenv so it is available in non-login shells too.
# Nothing to do here.
