# .zshenv is always sourced. It often contains exported variables that should be available to other programs.
[ -v DOT_DEBUG ] && echo '-> .zshenv'

export TERM="xterm-256color"
export LANG=en_US.UTF-8

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi