# sets the environment for interactive shells
[ -v DOT_DEBUG ] && echo '-> .zshrc'

# terminal
export EDITOR='vim'
# vi mode
bindkey -v

#zsh/oh-my-zsh
export ZSH_HOME=$HOME/.zsh
export ZSH=$HOME/.oh-my-zsh
export KEYTIMEOUT=5
ZSH_THEME=""
plugins=(zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# zsh-autosuggest
ZSH_AUTOSUGGEST_USE_ASYNC="true"
bindkey '^ ' forward-word # Ctrl+space

# keybindings
bindkey -v '^?' backward-delete-char
bindkey '^R' history-incremental-search-backward

# history file
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP

# fzf
if [ -f ~/.fzf.zsh ]; then
    source ~/.fzf.zsh
    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
    export FZF_CTRL_T_COMMAND="fd -t d . $PROJECTS_HOME"
fi

# functions
for function in $ZSH_HOME/functions/*; do
    source $function
done

# aliases
source $ZSH_HOME/aliases

# prompt
eval "$(starship init zsh)"

# completion; use cache if updated within 24h
fpath=($ZSH_HOME/completions /usr/local/share/zsh/site-functions $fpath)
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
  compinit -d ~/.zcompdump;
else
  compinit -C;
fi;