# sets the environment for interactive shells
[ -v DOT_DEBUG ] && echo '-> .zshrc'
# terminal
export EDITOR='vim'
# vi mode
bindkey -v

#zsh/oh-my-zsh
export ZSH_HOME=$HOME/.zsh
export ZSH=$HOME/.oh-my-zsh
export KEYTIMEOUT=5
ZSH_THEME=""
plugins=(zsh-autosuggestions zsh-syntax-highlighting)
fpath=($ZSH_HOME/completions ${HOMEBREW_PREFIX:-/usr/local}/share/zsh/site-functions(/N) $fpath)
source $ZSH/oh-my-zsh.sh

# zsh-autosuggest
ZSH_AUTOSUGGEST_USE_ASYNC="true"

# keybindings
bindkey '^ ' forward-word # Ctrl+space
bindkey -v '^?' backward-delete-char # Ctrl+?
bindkey '^R' history-incremental-search-backward # Ctrl+R

# history file
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP

# aws
if command -v aws &> /dev/null; then
  export AWS_PAGER=""
fi

# fzf
if [ -f ~/.fzf.zsh ]; then
    source ~/.fzf.zsh
    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
    if command -v fd &>/dev/null; then
        export FZF_CTRL_T_COMMAND="fd -t d . $PROJECTS_HOME"
    elif command -v fdfind &>/dev/null; then
        export FZF_CTRL_T_COMMAND="fdfind -t d . $PROJECTS_HOME"
    fi
fi

# golang
if command -v go &> /dev/null; then
  export GOROOT="$(go env GOROOT)"
  export GOPATH="$HOME/go"
  export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
fi

# nvm
export NVM_DIR="$HOME/.nvm"
if [[ "$OSTYPE" == darwin* ]]; then
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
    [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
else
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi

# functions
for fn in $ZSH_HOME/functions/*; do
    source $fn
done

# aliases
source $ZSH_HOME/aliases

# prompt
eval "$(starship init zsh)"

# git completion
zstyle ':completion:*:*:git:*' script "$HOME/.zsh/git-completion.bash"

# completion; use cache if updated within 24h
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
  compinit -d ~/.zcompdump;
else
  compinit -C;
fi;

autoload -U +X bashcompinit && bashcompinit
if command -v terraform &>/dev/null; then
  complete -o nospace -C "$(command -v terraform)" terraform
fi
if command -v aws_completer &>/dev/null; then
  complete -C aws_completer aws
fi
